# Reusable Workflow Scenario
#  Using environment secret passed down as input
#  Test for https://github.com/github/customer-feedback/issues/5627
name: RWF Reusable using environment secret passed as input

on:
  workflow_call:
    inputs:
      runson:
        type: string
      env:
        type: string

jobs:
  printenv:
    runs-on: ${{ inputs.runson }}
    environment: ${{ inputs.env }}
    steps:
    - name: Print Environment input
      run: echo ${{ inputs.env }}
    - name: Print Environment secret
      run: echo $key | rev
      env: 
        key: ${{ secrets.AZURE_KEY }}
