name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment_name:
        type: string

jobs:
  printenv:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    steps:
      - run: echo $PASSWORD | fold -s1
        env:
          PASSWORD: ${{secrets.PASSWORD}}
