name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  caller:
    uses: kyanny-corp-enterprise-cloud-testing/zd-1778988-5/.github/workflows/callee.yaml@main
    with:
      environment_name: prod
    secrets: inherit
